name: Semantic Release

on:
  push:
    branches:
      - main
      - next
      - next-major
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests (optional but recommended)
      - name: Run tests
        run: npm run test --if-present

      # Step 5: Build the project
      - name: Build
        run: npm run build --if-present

      # Step 6: Run semantic-release
      - name: Release
        uses: cycjimmy/semantic-release-action@v5
        id: semantic
        with:
          semantic_version: 24
          extra_plugins: |
            @semantic-release/changelog@v6
            @semantic-release/git@v10
            @semantic-release/github@v12
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              {name: 'next-major', prerelease: 'major'},
              {name: 'beta', prerelease: true},
              {name: 'alpha', prerelease: true}
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNNER_DEBUG: 1

      - name: Output release info
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "Release Version: ${{ steps.semantic.outputs.new_release_version }}"
          echo "Release Published: ${{ steps.semantic.outputs.new_release_published }}"
          echo "Release Notes: ${{ steps.semantic.outputs.new_release_notes }}"

      # using vercel to deploy
      # - name: Deploy to production
      #   if: steps.semantic.outputs.new_release_published == 'true'
      #   run: npm run deploy --if-present
      #   env:
      #     DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
